### ISSUE TITLE
Include Issue Title in Slack Messaging

### ISSUE THREAD

**Issue by bflad** [breathingdust/firewatch#1]
## Description

Currently Slack messages are sent as:

```
The following issues have recieved more than 10 in the configured interval:

---

https://github.com/hashicorp/terraform-provider-aws/issues/17943
```

It would be great if each issue was reported as either a title and text line:

```
Secrets Manager: Support Secret Replication: https://github.com/hashicorp/terraform-provider-aws/issues/17943
```

Or a Slack compatible link (I think it supports Markdown in this sense? I forget off top of head):

```
[Secrets Manager: Support Secret Replication](https://github.com/hashicorp/terraform-provider-aws/issues/17943)
```

**Comment by breathingdust** [comment]
Implemented via: https://github.com/breathingdust/firewatch/commit/751f60a7f90251757a5f0c3ff098568c9fe42d31
