### ISSUE TITLE
Clarify Slack Message Title Line

### ISSUE THREAD

**Issue by bflad** [breathingdust/firewatch#3]
## Description

Currently Slack messages are sent as:

```
The following issues have recieved more than 10 in the configured interval:

---

https://github.com/hashicorp/terraform-provider-aws/issues/17943
```

It currently has a minor typo for received and it might be worth calling out that the 10 is reactions count (👍 or generically just "reactions")  e.g.

```
The following issues have received more than 10 👍  reactions in the configured interval:
```

**Comment by breathingdust** [comment]
Fixed via: https://github.com/breathingdust/firewatch/commit/659a86db770a2f5f0b84fb21451100ae39fd0617#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R123
